//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prgGestionDeCompañias
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDPortafolioUcrEntities : DbContext
    {
        public BDPortafolioUcrEntities()
            : base("name=BDPortafolioUcrEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbArchivo> tbArchivos { get; set; }
        public virtual DbSet<tbAutore> tbAutores { get; set; }
        public virtual DbSet<tbBolsasEmpl> tbBolsasEmpls { get; set; }
        public virtual DbSet<tbCapacitacione> tbCapacitaciones { get; set; }
        public virtual DbSet<tbConvenio> tbConvenios { get; set; }
        public virtual DbSet<tbCorreo> tbCorreos { get; set; }
        public virtual DbSet<tbCurriculum> tbCurriculums { get; set; }
        public virtual DbSet<tbCurso> tbCursos { get; set; }
        public virtual DbSet<tbCursosLibr> tbCursosLibrs { get; set; }
        public virtual DbSet<tbDireccione> tbDirecciones { get; set; }
        public virtual DbSet<tbEmpresa> tbEmpresas { get; set; }
        public virtual DbSet<tbEspecialidadesPorExpe> tbEspecialidadesPorExpes { get; set; }
        public virtual DbSet<tbEspecialidadesTitu> tbEspecialidadesTitus { get; set; }
        public virtual DbSet<tbEstudiante> tbEstudiantes { get; set; }
        public virtual DbSet<tbExperienciasAcad> tbExperienciasAcads { get; set; }
        public virtual DbSet<tbGruposCur> tbGruposCurs { get; set; }
        public virtual DbSet<tbHerramienta> tbHerramientas { get; set; }
        public virtual DbSet<tbHerramientasProy> tbHerramientasProys { get; set; }
        public virtual DbSet<tbHorario> tbHorarios { get; set; }
        public virtual DbSet<tbMaterialesDida> tbMaterialesDidas { get; set; }
        public virtual DbSet<tbMiembro> tbMiembros { get; set; }
        public virtual DbSet<tbObservacionesProf> tbObservacionesProfs { get; set; }
        public virtual DbSet<tbPeriodosLaboProf> tbPeriodosLaboProfs { get; set; }
        public virtual DbSet<tbProfesore> tbProfesores { get; set; }
        public virtual DbSet<tbProyecto> tbProyectos { get; set; }
        public virtual DbSet<tbProyectosEmpresa> tbProyectosEmpresas { get; set; }
        public virtual DbSet<tbProyectosEstu> tbProyectosEstus { get; set; }
        public virtual DbSet<tbProyectosProf> tbProyectosProfs { get; set; }
        public virtual DbSet<tbPuestosProf> tbPuestosProfs { get; set; }
        public virtual DbSet<tbTelefono> tbTelefonos { get; set; }
        public virtual DbSet<tbTitulo> tbTitulos { get; set; }
        public virtual DbSet<tbTitulosProf> tbTitulosProfs { get; set; }
    }
}
