//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prgGestionDeCompañias
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDPortafolioUcrContext : DbContext
    {
        public BDPortafolioUcrContext()
            : base("name=BDPortafolioUcrContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbArchivos> tbArchivos { get; set; }
        public virtual DbSet<tbAutores> tbAutores { get; set; }
        public virtual DbSet<tbBolsasEmpl> tbBolsasEmpl { get; set; }
        public virtual DbSet<tbCapacitaciones> tbCapacitaciones { get; set; }
        public virtual DbSet<tbConvenios> tbConvenios { get; set; }
        public virtual DbSet<tbCorreos> tbCorreos { get; set; }
        public virtual DbSet<tbCurriculums> tbCurriculums { get; set; }
        public virtual DbSet<tbCursos> tbCursos { get; set; }
        public virtual DbSet<tbCursosLibr> tbCursosLibr { get; set; }
        public virtual DbSet<tbDirecciones> tbDirecciones { get; set; }
        public virtual DbSet<tbEmpresas> tbEmpresas { get; set; }
        public virtual DbSet<tbEspecialidadesPorExpe> tbEspecialidadesPorExpe { get; set; }
        public virtual DbSet<tbEspecialidadesProf> tbEspecialidadesProf { get; set; }
        public virtual DbSet<tbEspecialidadesTitu> tbEspecialidadesTitu { get; set; }
        public virtual DbSet<tbEstudiantes> tbEstudiantes { get; set; }
        public virtual DbSet<tbEstudiosProf> tbEstudiosProf { get; set; }
        public virtual DbSet<tbExperienciasAcad> tbExperienciasAcad { get; set; }
        public virtual DbSet<tbGruposCurs> tbGruposCurs { get; set; }
        public virtual DbSet<tbHerramientas> tbHerramientas { get; set; }
        public virtual DbSet<tbHerramientasProy> tbHerramientasProy { get; set; }
        public virtual DbSet<tbHorarios> tbHorarios { get; set; }
        public virtual DbSet<tbMaterialesDida> tbMaterialesDida { get; set; }
        public virtual DbSet<tbMiembros> tbMiembros { get; set; }
        public virtual DbSet<tbObservacionesProf> tbObservacionesProf { get; set; }
        public virtual DbSet<tbPeriodosLaboProf> tbPeriodosLaboProf { get; set; }
        public virtual DbSet<tbProfesores> tbProfesores { get; set; }
        public virtual DbSet<tbProyectos> tbProyectos { get; set; }
        public virtual DbSet<tbProyectosEmpresa> tbProyectosEmpresa { get; set; }
        public virtual DbSet<tbProyectosEstu> tbProyectosEstu { get; set; }
        public virtual DbSet<tbProyectosProf> tbProyectosProf { get; set; }
        public virtual DbSet<tbPuestosProf> tbPuestosProf { get; set; }
        public virtual DbSet<tbTelefonos> tbTelefonos { get; set; }
        public virtual DbSet<tbTitulosProf> tbTitulosProf { get; set; }
    }
}
