//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prgGestionDeCompañias
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCurso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbCurso()
        {
            this.tbGruposCurs = new HashSet<tbGruposCur>();
            this.tbCursos1 = new HashSet<tbCurso>();
            this.tbCursos = new HashSet<tbCurso>();
            this.tbCursos11 = new HashSet<tbCurso>();
            this.tbCursos2 = new HashSet<tbCurso>();
        }
    
        public int idCurso { get; set; }
        public string sigla { get; set; }
        public string nombre { get; set; }
        public string lugar { get; set; }
        public string ciclo { get; set; }
        public int creditos { get; set; }
        public byte[] programa { get; set; }
        public string estado { get; set; }
        public int totalHoras { get; set; }
        public string modalidad { get; set; }
        public string nombrePrograma { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbGruposCur> tbGruposCurs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCurso> tbCursos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCurso> tbCursos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCurso> tbCursos11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCurso> tbCursos2 { get; set; }
    }
}
