//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prgGestionDeCompañias
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDireccione
    {
        public int idDireccion { get; set; }
        public string tipoPersona { get; set; }
        public int idPersona { get; set; }
        public string direccion { get; set; }
        public string provincia { get; set; }
        public string canton { get; set; }
        public string distrito { get; set; }
    
        public virtual tbEmpresa tbEmpresa { get; set; }
        public virtual tbEstudiante tbEstudiante { get; set; }
        public virtual tbProfesore tbProfesore { get; set; }
    }
}
