//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prgGestionDeCompañias
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Globalization;

    public partial class tbEmpresas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbEmpresas()
        {
            this.tbBolsasEmpl = new HashSet<tbBolsasEmpl>();
            this.tbCorreos = new HashSet<tbCorreos>();
            this.tbDirecciones = new HashSet<tbDirecciones>();
            this.tbProyectosEmpresa = new HashSet<tbProyectosEmpresa>();
            this.tbPuestosProf = new HashSet<tbPuestosProf>();
            this.tbTelefonos = new HashSet<tbTelefonos>();
            this.tbCapacitaciones = new HashSet<tbCapacitaciones>();
            this.tbConvenios = new HashSet<tbConvenios>();
            this.tbMaterialesDida = new HashSet<tbMaterialesDida>();
        }

        [Required]
        [Display(Name = "Codigo de la Empresa")]
        public int idEmpresa { get; set; }

        [Required]
        [StringLength(100)]
        [Display(Name = "Nombre")]
        public string nombre { get; set; }

        [Required]
        [StringLength(1000)]
        [Display(Name = "Descripcion")]
        public string descripcionGene { get; set; }

        public byte[] foto { get; set; }

        [Required]
        [Display(Name = "Codigo de la Direccion")]
        public int idDireccion { get; set; }

        [Required]
        [StringLength(100)]
        [Display(Name = "Tipo de Persona")]
        public string tipoPersona { get; set; }

        [Required]
        [StringLength(1000)]
        [Display(Name = "Direccion")]
        public string direccion { get; set; }

        [Required]
        [StringLength(100)]
        [Display(Name = "Provincia")]
        public string provincia { get; set; }

        [Required]
        [StringLength(100)]
        [Display(Name = "Cantón")]
        public string canton { get; set; }

        [Required]
        [StringLength(100)]
        [Display(Name = "Distrito")]
        public string distrito { get; set; }

        [Required]
        [Display(Name = "Codigo del Telefono")]
        public int idTelefono { get; set; }

        //[Required]
        ////[StringLength(100)]
        //[Display(Name = "Telefono")]
        public int telefono { get; set; }

        [Required]
        [Display(Name = "Codigo del Correo")]
        public int idCorreo { get; set; }

        [Required]
        [StringLength(100)]
        [Display(Name = "Correo")]
        public string correo { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbBolsasEmpl> tbBolsasEmpl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCorreos> tbCorreos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDirecciones> tbDirecciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbProyectosEmpresa> tbProyectosEmpresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPuestosProf> tbPuestosProf { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbTelefonos> tbTelefonos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCapacitaciones> tbCapacitaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbConvenios> tbConvenios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbMaterialesDida> tbMaterialesDida { get; set; }
    }
}
