//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prgGestionDeCompañias
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbGruposCur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbGruposCur()
        {
            this.tbHorarios = new HashSet<tbHorario>();
            this.tbProfesores = new HashSet<tbProfesore>();
        }
    
        public int idGrupo { get; set; }
        public int idCurso { get; set; }
        public int numeroGrup { get; set; }
        public int cupoMaximo { get; set; }
        public int cupoMinimo { get; set; }
        public int cupoActual { get; set; }
    
        public virtual tbCurso tbCurso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbHorario> tbHorarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbProfesore> tbProfesores { get; set; }
    }
}
