//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prgGestionDeCompañias
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProfesore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbProfesore()
        {
            this.tbCorreos = new HashSet<tbCorreo>();
            this.tbCursosLibrs = new HashSet<tbCursosLibr>();
            this.tbDirecciones = new HashSet<tbDireccione>();
            this.tbObservacionesProfs = new HashSet<tbObservacionesProf>();
            this.tbPeriodosLaboProfs = new HashSet<tbPeriodosLaboProf>();
            this.tbProyectosEstus = new HashSet<tbProyectosEstu>();
            this.tbProyectosProfs = new HashSet<tbProyectosProf>();
            this.tbPuestosProfs = new HashSet<tbPuestosProf>();
            this.tbTelefonos = new HashSet<tbTelefono>();
            this.tbTitulosProfs = new HashSet<tbTitulosProf>();
            this.tbProyectos = new HashSet<tbProyecto>();
            this.tbEspecialidadesPorExpes = new HashSet<tbEspecialidadesPorExpe>();
            this.tbEspecialidadesTitus = new HashSet<tbEspecialidadesTitu>();
            this.tbExperienciasAcads = new HashSet<tbExperienciasAcad>();
            this.tbGruposCurs = new HashSet<tbGruposCur>();
            this.tbProyectos1 = new HashSet<tbProyecto>();
        }
    
        public int idProfesor { get; set; }
        public string nombre { get; set; }
        public string apellido1 { get; set; }
        public string apellido2 { get; set; }
        public string genero { get; set; }
        public System.DateTime fechaNaci { get; set; }
        public string jornada { get; set; }
        public string estado { get; set; }
        public string identificacion { get; set; }
        public string tipoIden { get; set; }
        public byte[] foto { get; set; }
        public byte[] curriculum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCorreo> tbCorreos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbCursosLibr> tbCursosLibrs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDireccione> tbDirecciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbObservacionesProf> tbObservacionesProfs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPeriodosLaboProf> tbPeriodosLaboProfs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbProyectosEstu> tbProyectosEstus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbProyectosProf> tbProyectosProfs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPuestosProf> tbPuestosProfs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbTelefono> tbTelefonos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbTitulosProf> tbTitulosProfs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbProyecto> tbProyectos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbEspecialidadesPorExpe> tbEspecialidadesPorExpes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbEspecialidadesTitu> tbEspecialidadesTitus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbExperienciasAcad> tbExperienciasAcads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbGruposCur> tbGruposCurs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbProyecto> tbProyectos1 { get; set; }
    }
}
