//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace prgGestionDeCompañias
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProyectos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbProyectos()
        {
            this.tbHerramientasProy = new HashSet<tbHerramientasProy>();
            this.tbProyectosEmpresa = new HashSet<tbProyectosEmpresa>();
            this.tbProyectosEstu = new HashSet<tbProyectosEstu>();
            this.tbProyectosProf = new HashSet<tbProyectosProf>();
            this.tbProfesores = new HashSet<tbProfesores>();
            this.tbMiembros = new HashSet<tbMiembros>();
            this.tbProfesores1 = new HashSet<tbProfesores>();
        }

        [Display(Name = "Codigo del Proyecto:")]
        public int idProyecto { get; set; }

        [Display(Name = "Nombre del Proyecto:")]
        public string nombre { get; set; }

        [Display(Name = "Descripción:")]
        public string descripcion { get; set; }

        [Display(Name = "Estado:")]
        public string estado { get; set; }

        [Display(Name = "Tipo:")]
        public string tipo { get; set; }

        [Display(Name = "Información:")]
        public byte[] informacion { get; set; }

        [Display(Name = "Nombre del Documento:")]
        public string nombreDocumento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbHerramientasProy> tbHerramientasProy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbProyectosEmpresa> tbProyectosEmpresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbProyectosEstu> tbProyectosEstu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbProyectosProf> tbProyectosProf { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbProfesores> tbProfesores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbMiembros> tbMiembros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbProfesores> tbProfesores1 { get; set; }
    }
}
