//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace prgGestionDeCompañias
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProyectosEmpresa
    {
        [Required]
        [StringLength(5)]
        [Display(Name = "Identificación de la Empresa:")]
        public int idEmpresa { get; set; }

        [Required]
        [StringLength(5)]
        [Display(Name = "Identificación del Proyecto:")]
        public int idProyecto { get; set; }

        [Required]
        [Display(Name = "Horas Invertidas:")]
        public int horasInvertidas { get; set; }

        public virtual tbEmpresas tbEmpresas { get; set; }
        public virtual tbProyectos tbProyectos { get; set; }
    }
}
