//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prgGestionDeCompañias
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPuestosProf
    {
        public int idProfesor { get; set; }
        public int idEmpresa { get; set; }
        public string puesto { get; set; }
        public string tiempoLabo { get; set; }
    
        public virtual tbEmpresa tbEmpresa { get; set; }
        public virtual tbProfesore tbProfesore { get; set; }
    }
}
