//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prgGestionDeCompañias
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTelefonos
    {
        public int idTelefono { get; set; }
        public int telefono { get; set; }
        public int idPersona { get; set; }
        public string tipoPers { get; set; }
    
        public virtual tbCapacitaciones tbCapacitaciones { get; set; }
        public virtual tbEmpresas tbEmpresas { get; set; }
        public virtual tbEstudiantes tbEstudiantes { get; set; }
        public virtual tbProfesores tbProfesores { get; set; }
    }
}
